// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: xref/xref.proto

package xref

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type XrefStatus_StatusEnum int32

const (
	XrefStatus_AVAILABLE   XrefStatus_StatusEnum = 0
	XrefStatus_UNAVAILABLE XrefStatus_StatusEnum = 1
)

// Enum value maps for XrefStatus_StatusEnum.
var (
	XrefStatus_StatusEnum_name = map[int32]string{
		0: "AVAILABLE",
		1: "UNAVAILABLE",
	}
	XrefStatus_StatusEnum_value = map[string]int32{
		"AVAILABLE":   0,
		"UNAVAILABLE": 1,
	}
)

func (x XrefStatus_StatusEnum) Enum() *XrefStatus_StatusEnum {
	p := new(XrefStatus_StatusEnum)
	*p = x
	return p
}

func (x XrefStatus_StatusEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (XrefStatus_StatusEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_xref_xref_proto_enumTypes[0].Descriptor()
}

func (XrefStatus_StatusEnum) Type() protoreflect.EnumType {
	return &file_xref_xref_proto_enumTypes[0]
}

func (x XrefStatus_StatusEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use XrefStatus_StatusEnum.Descriptor instead.
func (XrefStatus_StatusEnum) EnumDescriptor() ([]byte, []int) {
	return file_xref_xref_proto_rawDescGZIP(), []int{2, 0}
}

type XrefRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lastfour string `protobuf:"bytes,1,opt,name=lastfour,proto3" json:"lastfour,omitempty"`
}

func (x *XrefRequest) Reset() {
	*x = XrefRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xref_xref_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XrefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XrefRequest) ProtoMessage() {}

func (x *XrefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xref_xref_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XrefRequest.ProtoReflect.Descriptor instead.
func (*XrefRequest) Descriptor() ([]byte, []int) {
	return file_xref_xref_proto_rawDescGZIP(), []int{0}
}

func (x *XrefRequest) GetLastfour() string {
	if x != nil {
		return x.Lastfour
	}
	return ""
}

type XrefResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token *XREF `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *XrefResponse) Reset() {
	*x = XrefResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xref_xref_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XrefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XrefResponse) ProtoMessage() {}

func (x *XrefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xref_xref_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XrefResponse.ProtoReflect.Descriptor instead.
func (*XrefResponse) Descriptor() ([]byte, []int) {
	return file_xref_xref_proto_rawDescGZIP(), []int{1}
}

func (x *XrefResponse) GetToken() *XREF {
	if x != nil {
		return x.Token
	}
	return nil
}

type XrefStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *XrefStatus) Reset() {
	*x = XrefStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xref_xref_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XrefStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XrefStatus) ProtoMessage() {}

func (x *XrefStatus) ProtoReflect() protoreflect.Message {
	mi := &file_xref_xref_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XrefStatus.ProtoReflect.Descriptor instead.
func (*XrefStatus) Descriptor() ([]byte, []int) {
	return file_xref_xref_proto_rawDescGZIP(), []int{2}
}

type XREF struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *XREF) Reset() {
	*x = XREF{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xref_xref_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XREF) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XREF) ProtoMessage() {}

func (x *XREF) ProtoReflect() protoreflect.Message {
	mi := &file_xref_xref_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XREF.ProtoReflect.Descriptor instead.
func (*XREF) Descriptor() ([]byte, []int) {
	return file_xref_xref_proto_rawDescGZIP(), []int{3}
}

func (x *XREF) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type XrefSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalNew     int32 `protobuf:"varint,1,opt,name=total_new,json=totalNew,proto3" json:"total_new,omitempty"`
	TotalUpdated int32 `protobuf:"varint,2,opt,name=total_updated,json=totalUpdated,proto3" json:"total_updated,omitempty"`
	ElapsedTime  int32 `protobuf:"varint,3,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
}

func (x *XrefSummary) Reset() {
	*x = XrefSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xref_xref_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XrefSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XrefSummary) ProtoMessage() {}

func (x *XrefSummary) ProtoReflect() protoreflect.Message {
	mi := &file_xref_xref_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XrefSummary.ProtoReflect.Descriptor instead.
func (*XrefSummary) Descriptor() ([]byte, []int) {
	return file_xref_xref_proto_rawDescGZIP(), []int{4}
}

func (x *XrefSummary) GetTotalNew() int32 {
	if x != nil {
		return x.TotalNew
	}
	return 0
}

func (x *XrefSummary) GetTotalUpdated() int32 {
	if x != nil {
		return x.TotalUpdated
	}
	return 0
}

func (x *XrefSummary) GetElapsedTime() int32 {
	if x != nil {
		return x.ElapsedTime
	}
	return 0
}

var File_xref_xref_proto protoreflect.FileDescriptor

var file_xref_xref_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x78, 0x72, 0x65, 0x66, 0x2f, 0x78, 0x72, 0x65, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x78, 0x72, 0x65, 0x66, 0x22, 0x29, 0x0a, 0x0b, 0x58, 0x72, 0x65, 0x66, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x66, 0x6f,
	0x75, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x66, 0x6f,
	0x75, 0x72, 0x22, 0x30, 0x0a, 0x0c, 0x58, 0x72, 0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x78, 0x72, 0x65, 0x66, 0x2e, 0x58, 0x52, 0x45, 0x46, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x3a, 0x0a, 0x0a, 0x58, 0x72, 0x65, 0x66, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x2c, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x45, 0x6e, 0x75, 0x6d,
	0x12, 0x0d, 0x0a, 0x09, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x00, 0x12,
	0x0f, 0x0a, 0x0b, 0x55, 0x4e, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01,
	0x22, 0x1c, 0x0a, 0x04, 0x58, 0x52, 0x45, 0x46, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x72,
	0x0a, 0x0b, 0x58, 0x72, 0x65, 0x66, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1b, 0x0a,
	0x09, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6e, 0x65, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x65, 0x77, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x65, 0x6c, 0x61, 0x70, 0x73, 0x65, 0x64, 0x54, 0x69,
	0x6d, 0x65, 0x32, 0xe9, 0x01, 0x0a, 0x0b, 0x58, 0x72, 0x65, 0x66, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x58, 0x72, 0x65, 0x66, 0x12, 0x11, 0x2e,
	0x78, 0x72, 0x65, 0x66, 0x2e, 0x58, 0x72, 0x65, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x78, 0x72, 0x65, 0x66, 0x2e, 0x58, 0x72, 0x65, 0x66, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x58, 0x72, 0x65,
	0x66, 0x73, 0x12, 0x11, 0x2e, 0x78, 0x72, 0x65, 0x66, 0x2e, 0x58, 0x72, 0x65, 0x66, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x78, 0x72, 0x65, 0x66, 0x2e, 0x58, 0x72, 0x65,
	0x66, 0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x22, 0x00, 0x28, 0x01, 0x12, 0x37, 0x0a, 0x0b,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x58, 0x72, 0x65, 0x66, 0x73, 0x12, 0x10, 0x2e, 0x78, 0x72,
	0x65, 0x66, 0x2e, 0x58, 0x72, 0x65, 0x66, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x12, 0x2e,
	0x78, 0x72, 0x65, 0x66, 0x2e, 0x58, 0x72, 0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x37, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x58, 0x72, 0x65, 0x66,
	0x73, 0x12, 0x11, 0x2e, 0x78, 0x72, 0x65, 0x66, 0x2e, 0x58, 0x72, 0x65, 0x66, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x78, 0x72, 0x65, 0x66, 0x2e, 0x58, 0x72, 0x65, 0x66,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2d,
	0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x67, 0x65,
	0x6f, 0x72, 0x67, 0x69, 0x61, 0x64, 0x65, 0x73, 0x32, 0x37, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d,
	0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x78, 0x72, 0x65, 0x66, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_xref_xref_proto_rawDescOnce sync.Once
	file_xref_xref_proto_rawDescData = file_xref_xref_proto_rawDesc
)

func file_xref_xref_proto_rawDescGZIP() []byte {
	file_xref_xref_proto_rawDescOnce.Do(func() {
		file_xref_xref_proto_rawDescData = protoimpl.X.CompressGZIP(file_xref_xref_proto_rawDescData)
	})
	return file_xref_xref_proto_rawDescData
}

var file_xref_xref_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xref_xref_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_xref_xref_proto_goTypes = []interface{}{
	(XrefStatus_StatusEnum)(0), // 0: xref.XrefStatus.StatusEnum
	(*XrefRequest)(nil),        // 1: xref.XrefRequest
	(*XrefResponse)(nil),       // 2: xref.XrefResponse
	(*XrefStatus)(nil),         // 3: xref.XrefStatus
	(*XREF)(nil),               // 4: xref.XREF
	(*XrefSummary)(nil),        // 5: xref.XrefSummary
}
var file_xref_xref_proto_depIdxs = []int32{
	4, // 0: xref.XrefResponse.token:type_name -> xref.XREF
	1, // 1: xref.XrefService.GetXref:input_type -> xref.XrefRequest
	1, // 2: xref.XrefService.AddXrefs:input_type -> xref.XrefRequest
	3, // 3: xref.XrefService.GetAllXrefs:input_type -> xref.XrefStatus
	1, // 4: xref.XrefService.GetXrefs:input_type -> xref.XrefRequest
	2, // 5: xref.XrefService.GetXref:output_type -> xref.XrefResponse
	5, // 6: xref.XrefService.AddXrefs:output_type -> xref.XrefSummary
	2, // 7: xref.XrefService.GetAllXrefs:output_type -> xref.XrefResponse
	2, // 8: xref.XrefService.GetXrefs:output_type -> xref.XrefResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_xref_xref_proto_init() }
func file_xref_xref_proto_init() {
	if File_xref_xref_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xref_xref_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XrefRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xref_xref_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XrefResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xref_xref_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XrefStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xref_xref_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XREF); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xref_xref_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XrefSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xref_xref_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xref_xref_proto_goTypes,
		DependencyIndexes: file_xref_xref_proto_depIdxs,
		EnumInfos:         file_xref_xref_proto_enumTypes,
		MessageInfos:      file_xref_xref_proto_msgTypes,
	}.Build()
	File_xref_xref_proto = out.File
	file_xref_xref_proto_rawDesc = nil
	file_xref_xref_proto_goTypes = nil
	file_xref_xref_proto_depIdxs = nil
}
